# Generated by Django 3.1.6 on 2021-04-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='slot1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot1', to='app_one.course'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot2', to='app_one.course'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot3', to='app_one.course'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot4', to='app_one.course'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot5', to='app_one.course'),
        ),
    ]
